language: c

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      cache: apt
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libfuse-dev
      script:
        - ./build
        - modprobe fuse
        - ./nxfs -v
    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew update
        - brew tap caskroom/cask
        - brew cask install osxfuse
        - if [ -f /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs ]; then sudo chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs ; elif [ -f /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse ]; then sudo chmod +s /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse ; fi
      script:
        - ./build
        - if [ -f /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs ]; then sudo chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs ; elif [ -f /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse ]; then sudo chmod +s /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse ; fi
        - ./nxfs -v

