#!/bin/sh

dir=$(dirname $0)

olddir=$(pwd)
cd $dir
git pull origin master

echo ""
echo "Compiling and Stripping"
./build "$@" || exit 1

echo ""
echo "Packaging"
folder="nxfs-$(./nxfs -v 2>&1 | grep nxfs | sed 's/nxfs //g')-"
folder="${folder}$(gcc -dumpmachine)"

mkdir -p "$folder"
mv ./nxfs $folder/nxfs
git archive HEAD --prefix=src/ -o "$folder"/src.tar
cd "$folder"
tar xf src.tar
cd ..

rm "$folder".tar.xz
tar -cvJf "$folder".tar.xz \
    "$folder"/nxfs \
    "$folder"/src

echo ""
echo "Result:"
tar tf "$folder".tar.xz

rm -rf "$folder"

cd $olddir

